name: fastapi_seg_plan
channels:
  - conda-forge
  - defaults

dependencies:
  # Python version
  - python=3.12.9
  
  # Core libraries
  - pip=25.2
  - setuptools=80.9.0
  - wheel=0.45.1
  
  # Compression libraries
  - blosc=1.21.6
  - bzip2=1.0.8
  - lz4-c=1.10.0
  - lzo=2.10
  - snappy=1.2.2
  - xz=5.8.1
  - zlib=1.3.1
  - zstd=1.5.7
  
  # Geospatial libraries (for advanced GIS features)
  - gdal=3.11.4
  - geos=3.14.0
  - proj=9.7.0
  - libspatialite=5.1.0
  - librttopo=1.1.0
  - libkml=1.3.0
  - freexl=2.0.0
  
  # Image processing libraries
  - giflib=5.2.2
  - libjpeg-turbo=3.1.0
  - libpng=1.6.50
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - lerc=4.0.0
  - libjxl=0.11.1
  
  # Networking and security
  - openssl=3.5.4
  - krb5=1.21.3
  - c-ares=1.34.5
  - libcurl=8.14.1
  - libnghttp2=1.67.0
  - libssh2=1.11.1
  - ca-certificates=2025.10.5
  
  # XML parsing
  - libxml2=2.15.0
  - xerces-c=3.2.5
  - expat=2.7.1
  
  # Database
  - sqlite=3.50.2
  - libsqlite=3.50.4
  
  # Utilities
  - json-c=0.18
  - pcre2=10.46
  - icu=75.1
  - readline=8.3
  - ncurses=6.5
  - libedit=3.1.20250104
  - tk=8.6.15
  
  # Math libraries
  - libblas=3.9.0
  - libcblas=3.9.0
  - liblapack=3.9.0
  - libopenblas=0.3.30
  - muparser=2.3.5
  
  # Other libraries
  - libarchive=3.8.1
  - libhwy=1.3.0
  - minizip=4.0.10
  - uriparser=0.9.8
  - llvm-openmp=20.1.8
  
  # pip dependencies
  - pip:
      # FastAPI and web server
      - fastapi==0.109.0
      - uvicorn==0.27.0
      - uvloop==0.21.0
      - httptools==0.7.1
      - python-multipart==0.0.6
      - python-dotenv==1.0.0
      - watchfiles==1.1.1
      - websockets==15.0.1
      
      # Pydantic and validation
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pydantic-settings==2.1.0
      - annotated-types==0.7.0
      
      # HTTP clients
      - httpx==0.26.0
      - httpcore==1.0.9
      - h11==0.16.0
      - requests==2.32.5
      - urllib3==2.5.0
      - certifi==2025.10.5
      - idna==3.11
      
      # Deep Learning - PyTorch
      - torch==2.8.0
      - torchvision==0.23.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      
      # Scientific computing
      - numpy==1.26.3
      - scipy==1.16.2
      - scikit-learn==1.7.2
      - scikit-image==0.25.2
      - numba==0.62.1
      - llvmlite==0.45.1
      
      # Image processing
      - opencv-python==4.9.0.80
      - pillow==10.2.0
      - imageio==2.37.0
      - tifffile==2025.10.4
      
      # Data visualization
      - matplotlib==3.10.7
      
      # Geospatial data processing
      - rasterio==1.3.9
      - shapely==2.0.2
      - affine==2.4.0
      - geopy==2.4.1
      - geographiclib==2.1
      - snuggs==1.4.7
      - cligj==0.7.2
      - click-plugins==1.1.1.2
      
      # Graph and network analysis
      - networkx==3.5
      - sknw==0.15
      
      # Utilities
      - tqdm==4.67.1
      - click==8.3.0
      - pyyaml==6.0.3
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - joblib==1.5.2
      - threadpoolctl==3.6.0
      - packaging==25.0
      - filelock==3.20.0
      - fsspec==2025.9.0
      - lazy-loader==0.4
      
      # Template engine
      - jinja2==3.1.6
      - markupsafe==3.0.3
      
      # Math and symbolic computation
      - sympy==1.14.0
      - mpmath==1.3.0
      
      # Plotting utilities
      - cycler==0.12.1
      - kiwisolver==1.4.9
      - fonttools==4.60.1
      - pyparsing==3.2.5
      - contourpy==1.3.3
      
      # AWS SDK
      - boto3==1.34.24
      - botocore==1.34.162
      - s3transfer==0.10.4
      - jmespath==1.0.1
      
      # Security and authentication
      - cryptography==46.0.2
      - passlib==1.7.4
      - python-jose==3.3.0
      - bcrypt==5.0.0
      - ecdsa==0.19.1
      - pyasn1==0.6.1
      - rsa==4.9.1
      - cffi==2.0.0
      - pycparser==2.23
      
      # Async utilities
      - anyio==4.11.0
      - sniffio==1.3.1
      - aiofiles==23.2.1
      
      # Starlette (FastAPI dependency)
      - starlette==0.35.1
      
      # Date/time utilities
      - python-dateutil==2.9.0.post0
      
      # Other utilities
      - attrs==25.4.0
      - six==1.17.0
      - typing-extensions==4.15.0
      - protobuf==6.32.1
      - markdown==3.9
      - grpcio==1.75.1
      - absl-py==2.3.1
      - werkzeug==3.1.3
      - railway==0.0.4
